### ISSUE TITLE
Anyone else had to 'nvidia-xconfig' before overclock works?

### ISSUE THREAD

**Issue by blacksoil** [Cyclenerd/ethereum_nvidia_miner#42]
First of all, thanks a bunch to Cyclenerd who created this awesome Linux image :)

I just wanna share that yesterday I couldn't get OC to work out of the box. After researching a bit, I found that I had to run the following command, before the OC script worked:
`sudo nvidia-xconfig -a --allow-empty-initial-configuration --cool-bits=28 --use-display-device="DFP-0" --connected-monitor="DFP-0"`

Just in case this can be helpful for others, I'm sharing it here. Did anybody experience this as well?

**Comment by Cyclenerd** [comment]
Please look in the manual. Did you run `setup`? Especially point 6.

**Comment by n4ru** [comment]
I've ran setup and tried this command, but it didn't seem to help much. My cards don't seem to be overclocked. I'm getting hashrates in the ~160MHs versus the 200MHs I get in Windows.  I've ran the setup, set my clocks, went into settings to change it from `{0..5}` to `{0..7}` (since I have 8 cards).

Weirder still is that when I go into nvidia-smi, my last card is running 10W lower and ~150MHz lower than I have set. Is there another step I'm missing? I'm running all GTX 1060s, so it's impossible that it's just one card not being overclocked causing the 40MHs drop.

**Comment by h-town** [comment]
check whether or not nvidia-smi shows Xorg attached to the GPU rather than
just the miner executable.  if not, it's a pretty good indication that you
need to adjust /etc/X11/xorg.conf.  nvidia-settings won't affect the GPU
unless it's known by X.

**Comment by n4ru** [comment]
Deleted my originally to confirm some issues, but it looks like I'm still having them. x is running on each GPU.

> I've ran setup and tried this command, but it didn't seem to help much. My cards don't seem to be overclocked. I'm getting hashrates in the ~160MHs versus the 200MHs I get in Windows.  I've ran the setup, set my clocks, went into settings to change it from `{0..5}` to `{0..7}` (since I have 8 cards).
> 
> Weirder still is that when I go into nvidia-smi, my last card is running 10W lower and ~150MHz lower than I have set. Is there another step I'm missing? I'm running all GTX 1060s, so it's impossible that it's just one card not being overclocked causing the 40MHs drop.

**Comment by Cyclenerd** [comment]
I think this is off topic. The topic is "Anyone else had to 'nvidia-xconfig' before overclock works?"  But... Could have been related to: https://github.com/Cyclenerd/ethereum_nvidia_miner#known-issues
